### ISSUE TITLE
Casting issue

### ISSUE THREAD

**Issue by RishabhMaheshwari** [bizz84/coding-with-flutter-login-demo#2]
compiler message: lib/root_page.dart:57:24: Error: A value of type '#lib1::BaseAuth' can't be assigned to a variable of type '#lib2::BaseAuth'.
compiler message: Try changing the type of the left hand side, or casting the right hand side to '#lib2::BaseAuth'.
compiler message:           auth: widget.auth,
compiler message:                        ^
Compiler failed on C:\Users\Dell-pc\AndroidStudioProjects\login_app\lib\main.dart

FAILURE: Build failed with an exception.

**Comment by bramblettd** [comment]
I am having the same issue. Did you find the solution? Or any more info?

**Comment by bizz84** [comment]
Hi all, this happens when using a relative path in the `imports`.

I have updated the source code to use absolute paths only. For the `root_page.dart` it now looks like this:

```dart
import 'package:flutter/material.dart';
import 'package:login_demo/auth.dart';
import 'package:login_demo/home_page.dart';
import 'package:login_demo/login_page.dart';
```

I'm closing this issue - let me know if it solves your problem.

**Comment by juancarlosjr97** [comment]
Hi there,

Thank @bizz84 

It works !
