### ISSUE TITLE
Userid

### ISSUE THREAD

**Issue by maah75** [bizz84/coding-with-flutter-login-demo#6]
Hi how can I get user ID with AouthProvider.of(context).aouth.surentUser();

I want to get user ID as setting in different page

Thank you love your work

**Comment by maah75** [comment]
I got it Thanks ^_^

**Comment by FredvanRijswijk** [comment]
> ot it Thanks ^_

Can you give the solution?

**Comment by maah75** [comment]
i'm not sure if this is the right solution but it is work for me

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    var auth = AuthProvider.of(context).auth;
    auth.currentUser().then((userId) {
      setState(() {
        userid = userId;
      });
    });
  }

^_^
